name: my_getx_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  shared_preferences: ^2.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^1.1.3
  # a convenient code generator for get_it
  injectable_generator: ^1.5.3
  mockito: ^5.3.2 # Create Mock
  mocktail: ^0.2.0 # Create Mock
  build_runner: ^2.2.0
  http_mock_adapter: ^0.3.3
  
flutter:
  uses-material-design: true

 
